name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: npm install
        run: npm install
      - name: test-coverage
        run: npm run test:coverage
          