name: ci-typescript-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  all:
    name: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js $
      uses: actions/setup-node@v2
      with:
        node-version: $
        cache: 'npm'
    - name: npm install
      run: npm install
    - name: npm lint
      run: npm run lint
    - name: npm test
      run: npm run test