name: ci
on: 
  pull_request:
    branches:
      - develop

jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      #with:
      #  node-version: $
      #  cache: 'npm'
    - name: npm install
      run: npm install
    - name: npm lint
      run: npm run lint
    - name: npm test
      run: npm run test
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: marcusbalbi/ci-full-cycle-example:latest